const usernames = [
   'aspdi',
   'bagoshark',
   'baltim',
   'cruelmh',
   'doodlesumo',
   'enecsid',
   'fairylol',
   'forava',
   'funll',
   'gamertwist',
   'hanger',
   'infour',
   'islesco',
   'loveshuman',
   'megsus',
   'moom',
   'musicle',
   'ninjacq',
   'nychell',
   'onlinewacky',
   'papergreat',
   'rightsc',
   'rodeolo',
   'shortra',
   'sorbox',
   'thackli',
   'thamiq',
   'trammon',
   'twoyeom',
   'wirery',
   'blondiant',
   'brectino',
   'chikkavan',
   'comtersbu',
   'conroest',
   'cundaydon',
   'glamourgiga',
   'gormator',
   'greydubya',
   'guantomark',
   'joshsmarter',
   'kenjianch',
   'krediafl',
   'leveliadv',
   'luvteng',
   'nexthmic',
   'pakenryo',
   'papabody',
   'pathcrakh',
   'phreekjide',
   'plentymula',
   'rawhilogi',
   'replecon',
   'reveloy',
   'rollblich',
   'salpaxwoo',
   'thiefshay',
   'twocher',
   'unshiya',
   'zestediz',
   'abmhony',
   'accula',
   'airsin',
   'animeth',
   'axionsi',
   'booster',
   'campyja',
   'campytreasure',
   'drummerradio',
   'earpo',
   'elementkeeper',
   'guantocotton',
   'guantone',
   'heados',
   'imette',
   'inormi',
   'lawxan',
   'logicmaid',
   'mobiloc',
   'moviesnoop',
   'nocket',
   'notesnarrative',
   'objerr',
   'punk',
   'romantichell',
   'spazer',
   'storiesha',
   'topicsch',
   'valuedim',
   'vulturegazer',
   'basentra',
   'biggatch',
   'buffyprank',
   'bullul',
   'championordi',
   'crazyomet',
   'darthtrimble',
   'flyrk',
   'girley',
   'gourarill',
   'grantconfident',
   'heareepi',
   'homeffe',
   'idiotorma',
   'ionya',
   'lolallst',
   'mintai',
   'nycrl',
   'ogicalli',
   'perfelled',
   'phator',
   'phobicfeisty',
   'presslive',
   'sandra',
   'sizzlinproud',
   'snoopenta',
   'songal',
   'talevest',
   'tillysitu',
   'warmfighter'
]

const strings = [
   'consequat esse ullamco dolore deserunt ad lorem.',
   'nulla officia et voluptate velit ea dolor laboris veniam.',
   'elit dolore aliquip laborum adipisicing excepteur veniam minim in id.',
   'culpa dolor culpa aliqua amet adipisicing lorem reprehenderit eiusmod cupidatat voluptate eu tempor eiusmod.',
   'culpa consectetur qui do quis non do consectetur cillum veniam sint cupidatat cupidatat.',
   'irure minim aute nisi mollit minim sunt aute nulla anim magna ullamco qui enim.',
   'voluptate qui eu magna excepteur elit ex enim ea eiusmod est tempor in.',
   'nulla sunt irure et lorem minim duis.',
   'laborum ea ipsum aliquip excepteur enim occaecat.',
   'elit excepteur ad ipsum cillum nulla aliqua consequat nostrud velit velit qui dolore ea tempor.',
   'duis deserunt magna voluptate ullamco est pariatur in excepteur nostrud ex.',
   'tempor lorem veniam aute fugiat officia veniam dolore qui tempor in.',
   'culpa consequat eiusmod anim in.',
   'excepteur ipsum tempor esse quis elit consequat et consequat ad.',
   'consectetur do culpa et fugiat pariatur.',
   'et adipisicing magna minim et laboris.',
   'enim sit culpa aliqua laborum.',
   'deserunt proident voluptate laboris quis enim anim aliqua est do.',
   'et sint officia duis sunt incididunt fugiat et laboris cillum.',
   'ut nisi veniam ullamco proident dolore tempor reprehenderit duis enim nisi laborum.',
   'sint reprehenderit ipsum anim do pariatur.',
   'excepteur cillum sunt est ea dolor do id reprehenderit labore velit qui.',
   'do ad eu anim quis eu excepteur irure elit sint velit in cillum.',
   'proident adipisicing aute ea aliqua exercitation fugiat mollit reprehenderit non esse.',
   'ullamco id ex laborum laborum.',
   'anim pariatur non reprehenderit enim consectetur culpa cillum enim excepteur lorem sit.',
   'mollit officia pariatur laboris dolor anim ad lorem voluptate.',
   'occaecat voluptate laboris ut veniam incididunt cupidatat sint ex qui do qui ipsum.',
   'consequat nostrud voluptate consequat laboris culpa pariatur in cupidatat.',
   'dolore eu tempor enim id cillum nulla sunt lorem.',
   'cupidatat ea aliquip tempor id sunt fugiat irure dolore cupidatat in ex occaecat ex.',
   'id est irure ea sunt do reprehenderit lorem eiusmod.',
   'voluptate irure dolore ea est cillum.',
   'adipisicing quis voluptate do ad.',
   'qui aliquip ut est eiusmod pariatur eiusmod tempor ut consequat ex voluptate magna irure excepteur.',
   'excepteur aute aliqua minim nisi qui eu voluptate exercitation ut ea aliquip aliqua.',
   'irure ex ad nulla deserunt sit nisi fugiat qui cillum ex cillum amet.',
   'excepteur do lorem ut consectetur tempor lorem esse lorem qui anim aute proident duis mollit.',
   'ut cillum elit pariatur ut dolor mollit laboris nostrud.',
   'aliqua lorem dolore nostrud aliquip ut deserunt esse ullamco pariatur ea.',
   'do qui veniam nulla sit id incididunt esse magna laborum ullamco lorem.',
   'culpa aute nisi do anim do et ullamco amet qui.',
   'velit nulla id labore ea.',
   'occaecat laborum occaecat est sunt voluptate occaecat sint laborum lorem reprehenderit eiusmod mollit sunt.',
   'exercitation ex ipsum consequat velit tempor quis excepteur proident.',
   'excepteur labore sit nulla et incididunt anim mollit fugiat quis fugiat qui fugiat proident.',
   'non exercitation ad dolore sint aute sit occaecat tempor ea irure aliqua.',
   'est elit laboris ipsum est anim cillum sunt sint laborum.',
   'duis ad ullamco culpa tempor esse magna non eu duis dolore.',
   'consectetur ipsum occaecat laborum nostrud aute reprehenderit voluptate amet consequat est minim do elit.',
   'nisi ex non eiusmod quis amet ut amet anim exercitation occaecat consectetur deserunt cupidatat commodo.',
   'id aliqua velit ad fugiat incididunt sint qui non.',
   'aute in voluptate in anim qui incididunt.',
   'nulla elit officia deserunt excepteur sit occaecat reprehenderit consequat sit enim ipsum eu.',
   'lorem elit tempor ea magna sint cupidatat veniam excepteur nisi.',
   'id ipsum nisi eu consequat.',
   'officia commodo occaecat dolor velit.',
   'esse ad ad do commodo et deserunt.',
   'laborum non et sint anim dolore.',
   'lorem nulla commodo laborum proident aute ullamco ad proident consequat ipsum ullamco.',
   'aliquip mollit occaecat ad consectetur occaecat esse ea qui tempor ad incididunt mollit.',
   'aliquip consectetur veniam pariatur duis incididunt.',
   'sunt cillum et amet veniam.',
   'incididunt amet reprehenderit do labore dolor commodo occaecat labore sit proident consequat reprehenderit irure non.',
   'laborum et adipisicing non veniam eiusmod irure nisi in.',
   'est velit non aute consequat enim.',
   'id duis consequat do minim quis nulla quis irure.',
   'enim id id incididunt magna id tempor ad quis ex laborum aliquip.',
   'nisi aliquip laborum elit pariatur cupidatat irure esse nulla.',
   'officia nisi velit exercitation et labore qui duis culpa minim esse proident amet voluptate.',
   'occaecat officia ad adipisicing est sit sit consequat id aliqua velit officia in mollit aute.',
   'nisi deserunt veniam sunt mollit.',
   'exercitation deserunt ut culpa laborum minim labore.',
   'sunt ullamco ullamco velit nulla voluptate quis.',
   'anim officia ex deserunt cillum ut proident commodo enim sint.',
   'duis elit amet incididunt deserunt qui laboris laborum labore consequat sit non ipsum.',
   'incididunt consequat consequat adipisicing ea nisi laboris dolor minim eu.',
   'elit pariatur id velit ipsum cillum aliquip ullamco incididunt duis cupidatat magna.',
   'incididunt nisi duis non ad laborum pariatur.',
   'anim duis sunt consectetur do enim et cupidatat nulla.',
   'proident duis pariatur eiusmod aute irure enim aliqua proident voluptate amet lorem deserunt.',
   'qui cillum magna occaecat sunt culpa et aliqua non.',
   'aliqua adipisicing veniam minim dolor sint ex occaecat est cillum minim elit.',
   'irure culpa nulla cillum labore id aute velit occaecat commodo esse sunt non ad est.',
   'ullamco non enim deserunt proident veniam qui velit lorem non nisi sunt.',
   'officia officia laborum enim reprehenderit non.',
   'proident eu sit magna cillum cillum aute aliquip reprehenderit laborum elit ipsum incididunt.',
   'dolor laboris adipisicing laboris mollit in deserunt sunt id voluptate est magna eu velit.',
   'velit est et dolor qui fugiat magna sint ad elit amet sint eu fugiat.',
   'occaecat dolor voluptate laboris ad fugiat quis tempor exercitation lorem cillum sunt mollit.',
   'non incididunt aute aliqua qui mollit magna consequat occaecat aliquip quis elit voluptate deserunt.',
   'qui est laborum esse dolor.',
   'esse dolor et ad velit enim dolore.',
   'officia sint minim nulla cupidatat ex proident tempor labore aliqua nisi veniam est.',
   'magna elit aute ad enim ullamco laborum reprehenderit ex.',
   'reprehenderit nostrud labore adipisicing labore do voluptate enim enim ea esse ea nostrud reprehenderit.',
   'dolor sint occaecat do dolor do nostrud velit deserunt incididunt ipsum consequat.',
   'dolor consequat magna elit ipsum.',
   'culpa sit nisi occaecat pariatur magna consequat labore reprehenderit irure eu consequat enim cillum enim.',
   'irure minim veniam sit deserunt qui.',
   'in ea elit consequat ad dolor lorem ea eiusmod.',
   'enim nostrud occaecat deserunt excepteur cupidatat est et et anim ipsum sit occaecat nostrud.',
   'lorem nisi enim cupidatat ipsum dolore quis.',
   'magna tempor dolore lorem lorem veniam occaecat consequat occaecat consectetur quis culpa.',
   'voluptate culpa excepteur esse enim.',
   'non voluptate sint eiusmod pariatur ipsum dolore proident dolor magna.',
   'adipisicing cupidatat id sint aute sunt sit.',
   'aliquip elit fugiat aliquip esse eiusmod aliqua nisi velit voluptate.',
   'anim qui dolore ex ex eu occaecat laborum lorem nisi consectetur.',
   'elit ullamco est deserunt occaecat anim ad est proident nulla laboris tempor.',
   'eiusmod nostrud et ipsum ut do amet commodo mollit.',
   'duis eiusmod id est ut reprehenderit aliqua nostrud lorem magna enim officia.',
   'laboris do laboris deserunt duis culpa do.'
]

const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomUsername = () => {
   const i = Math.floor(Math.random() * usernames.length);
   const result = usernames[i];
   usernames.splice(i, 1);
   return result;
}

const getRandomStringArr = (int) => {
   const results = [];
   for (let i = 0; i < int; i++) {
      results.push(getRandomArrItem(strings));
   }
   return results;
}

module.exports = { getRandomUsername, getRandomStringArr, getRandomArrItem }